apiVersion: apps/v1
kind: Deployment
metadata:
  name: kaizer-portfolio-deployment-production
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kaizer-portfolio-production
  template:
    metadata:
      labels:
        app: kaizer-portfolio-production
    spec:
      containers:
        - name: kaizer-portfolio-container-production
          image: ghcr.io/kaizerpwn/kaizer-portfolio-next:ee4c5c48fe3f27783b400df42e75fe7e88591760
          ports:
            - containerPort: 3000
      imagePullSecrets:
        - name: regcred
