apiVersion: apps/v1
kind: Deployment
metadata:
  name: kaizer-portfolio-deployment-production
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: kaizer-portfolio-production
  template:
    metadata:
      labels:
        app: kaizer-portfolio-production
    spec:
      nodeSelector:
        kubernetes.io/arch: arm64
      containers:
        - name: kaizer-portfolio-container-production
          image: ghcr.io/kaizerpwn/kaizer-portfolio-next:6337157a7dd88821f47ef3a4e6b42abf0401b27b
          ports:
            - containerPort: 3000
      imagePullSecrets:
        - name: regcred
