apiVersion: apps/v1
kind: Deployment
metadata:
  name: kaizer-portfolio-deployment-production
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kaizer-portfolio-production
  template:
    metadata:
      labels:
        app: kaizer-portfolio-production
    spec:
      nodeSelector:
        kubernetes.io/arch: arm64
      containers:
        - name: kaizer-portfolio-container-production
          image: ghcr.io/kaizerpwn/kaizer-portfolio-next:c716667c3dd87a42bcf123c2b45c1fdf4162de53
          ports:
            - containerPort: 3000
      imagePullSecrets:
        - name: regcred
