apiVersion: apps/v1
kind: Deployment
metadata:
  name: crazy-donut-backend-deployment-production
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: crazy-donut-backend-production
  template:
    metadata:
      labels:
        app: crazy-donut-backend-production
    spec:
      nodeSelector:
        kubernetes.io/arch: arm64
      containers:
        - name: crazy-donut-backend-container-production
          image: ghcr.io/kaizerpwn/crazy-donut-backend:93886f414d8873ccef0d5d41e23f5b3c26beacff
          ports:
            - containerPort: 8000
      imagePullSecrets:
        - name: regcred
