apiVersion: apps/v1
kind: Deployment
metadata:
  name: crazy-donut-frontend-deployment-production
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: crazy-donut-frontend-production
  template:
    metadata:
      labels:
        app: crazy-donut-frontend-production
    spec:
      nodeSelector:
        kubernetes.io/arch: arm64
      containers:
        - name: crazy-donut-frontend-container-production
          image: ghcr.io/kaizerpwn/crazy-donut-frontend:413b7597b33b092c8f4b98f260bc2e18f454424d
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: regcred
