apiVersion: v1
kind: Service
metadata:
  name: crazy-donut-service-production
spec:
  type: LoadBalancer
  selector:
    app: crazy-donut-production
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
