apiVersion: v1
kind: Secret
metadata:
  name: venezuela-launcher-api-secret
type: Opaque
data:
  DB_USER: cm9vdA==
  DB_PASS: TWF0aWNEZG9zZXJHbGF2bmkwMzIwMDMh
  JWT_SECRET_KEY: ZXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5
