apiVersion: apps/v1
kind: Deployment
metadata:
  name: netflix-next-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: netflix-next
  template:
    metadata:
      labels:
        app: netflix-next
    spec:
      containers:
        - name: netflix-next-container
          image: ghcr.io/kaizerpwn/nextjs-app:4606905767fc7673b9f7a91a5a98d9b3321dc382
          ports:
            - containerPort: 3000
      imagePullSecrets:
        - name: regcred
