apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: netflix-next-ingress
spec:
  rules:
    - host: netflix-next.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: netflix-next-service
                port:
                  number: 80
