apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: netflix-next-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging
spec:
  rules:
    - host: netflix.kaizer.live
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: netflix-next-service
                port:
                  number: 80
  tls:
    - hosts:
        - netflix.kaizer.live
      secretName: netflix-next-tls
