apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin-venezuela-deployment-staging
  namespace: venezuela
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: phpmyadmin-venezuela-staging
  template:
    metadata:
      labels:
        app: phpmyadmin-venezuela-staging
    spec:
      containers:
        - name: phpmyadmin
          image: phpmyadmin:latest
          env:
            - name: PMA_HOST
              value: mariadb-service-venezuela-staging
            - name: PMA_PORT
              value: "3306"
            - name: PMA_ARBITRARY
              value: "1"
            - name: MYSQL_ROOT_PASSWORD
              value: JoyRootPassword333!
            - name: PHP_UPLOAD_MAX_FILESIZE
              value: "50M"
            - name: PHP_POST_MAX_SIZE
              value: "50M"
            - name: PHP_MAX_EXECUTION_TIME
              value: "300"
          ports:
            - containerPort: 80
              name: phpmyadmin
