apiVersion: apps/v1
kind: Deployment
metadata:
  name: carbo-deployment-production
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: carbo-production
  template:
    metadata:
      labels:
        app: carbo-production
    spec:
      dnsConfig:
        options:
          - name: ndots
            value: "1"
      nodeSelector:
        kubernetes.io/arch: arm64
      containers:
        - name: carbo-container-production
          image: ghcr.io/kaizerpwn/carbo-hackathon:223c4ed5b6c91eae500b142b94879b96eab831f5
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_URL
              value: "mysql://carbo:Yeo0uMIPP8Fcybe@mariadb-service-carbo-production:3306/carbo"
            - name: PRISMA_CLIENT_ENGINE_TYPE
              value: "binary"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: openai-api-secret
                  key: JWT_SECRET
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: openai-api-secret
                  key: OPENAI_API_KEY
      imagePullSecrets:
        - name: regcred
