apiVersion: apps/v1
kind: Deployment
metadata:
  name: carbo-deployment-production
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: carbo-production
  template:
    metadata:
      labels:
        app: carbo-production
    spec:
      dnsConfig:
        options:
          - name: ndots
            value: "1"
      nodeSelector:
        kubernetes.io/arch: arm64
      containers:
        - name: carbo-container-production
          image: ghcr.io/kaizerpwn/carbo-hackathon:09cd2568dbbdcafebefcbe72cca576a6408cb53b
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_URL
              value: "mysql://carbo:Yeo0uMIPP8Fcybe@mariadb-service-carbo-production:3306/carbo"
            - name: PRISMA_CLIENT_ENGINE_TYPE
              value: "binary"
            - name: JWT_SECRET
              value: "ibrakadabra"
            - name: OPENAI_API_KEY
              value: "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"
      imagePullSecrets:
        - name: regcred
